backbone: GCN
dataset_name: actor
batch_size: 10
data_dir: ./data/
data_seed: 1234
data_type: network
hidden_size: 32
graph_learn_num_pers: 4
dropout: 0.5
eps_adj: 4e-5
weight_decay: 5.0e-05
random_seed: 1234
verbose: 20
eary_stop_metric: acc
patience: 1000
print_every_epochs: 500
graph_learn: true
graph_learn_epsilon: 0.5
graph_learn_ratio: 0.7
sparsity_ratio: 0
update_adj_ratio: 0.1
smoothness_ratio: 0
use_pri: 1
pri_loss_weight: 1
beta: 1
use_wave: 1
wave_learn_shape: 16
wave_weight: 0.01
